# classickong.r65 - Makefile for SNES development with WLA-DX
# Generated by R65 project management tool

# Project configuration
PROJECT = CLASSICKONG.R65
MAIN_SRC = src/main.r65
BUILD_DIR = build
ROM_FILE = $(BUILD_DIR)/$(PROJECT).smc

# Tools
R65C = python -m r65.compiler.main
WLA = wla-65816
WLA_LINK = wlalink

# Flags
WLA_FLAGS = -o
R65C_FLAGS = -v --cfg snes --dbg

# Default target
all: $(ROM_FILE)

# Compile R65 source to WLA-DX assembly
$(BUILD_DIR)/main.asm: $(MAIN_SRC) $(wildcard src/lib/*.r65)
	@mkdir -p $(BUILD_DIR)
	$(R65C) $(MAIN_SRC) -o $@ $(R65C_FLAGS)

# Assemble WLA-DX object file
# Run from src/ directory so relative paths in INCBIN work correctly
$(BUILD_DIR)/main.o: $(BUILD_DIR)/main.asm
	cd src && $(WLA) $(WLA_FLAGS) ../build/main.o ../build/main.asm

# Link object file to ROM
$(ROM_FILE): $(BUILD_DIR)/main.o
	@echo "[LINK] $@"
	@echo "[objects]" > linkfile.txt
	@echo "$<" >> linkfile.txt
	$(WLA_LINK) -v -S linkfile.txt $@
	@rm linkfile.txt

# Build using r65x (alternative method)
r65x-build:
	r65x build

# Clean build artifacts
clean:
	@echo "[CLEAN] Removing build artifacts..."
	rm -rf $(BUILD_DIR)
	rm -f *.o *.asm *.smc *.sym *.map linkfile.txt

# Install dependencies
install-deps:
	@echo "[INSTALL] Installing WLA-DX..."
	pip install wla-dx

# Run with emulator (requires BSNES or higan)
run: $(ROM_FILE)
	@if command -v Mesen >/dev/null 2>&1; then \
		Mesen $(ROM_FILE); \
	elif command -v higan >/dev/null 2>&1; then \
		higan $(ROM_FILE); \
	elif command -v bsnes >/dev/null 2>&1; then \
		bsnes $(ROM_FILE); \
	else \
		echo "No compatible emulator found. Install bsnes or higan."; \
		echo "Then run: make run"; \
	fi

# Debug with verbose output
debug: clean
	$(MAKE) all R65C_FLAGS="-v"

# Check syntax only (no ROM generation)
syntax: $(BUILD_DIR)/main.asm

# Show help
help:
	@echo "Available targets:"
	@echo "  all          - Build ROM (default)"
	@echo "  r65x-build   - Build using r65x tool"
	@echo "  clean        - Remove build artifacts"
	@echo "  install-deps - Install WLA-DX dependencies"
	@echo "  run          - Run ROM with emulator"
	@echo "  debug        - Build with verbose output"
	@echo "  syntax       - Check syntax only"
	@echo "  help         - Show this help"

# Debug print variables
debug-vars:
	@echo "PROJECT: $(PROJECT)"
	@echo "MAIN_SRC: $(MAIN_SRC)"
	@echo "ROM_FILE: $(ROM_FILE)"

.PHONY: all clean install-deps run debug syntax r65x-build help debug-vars
